In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Collect and prepare data

In [2]:
df = pd.read_csv('Salary_Data.csv')

In [3]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
df.shape

(30, 2)

In [9]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split_test_split

In [11]:
X = df.YearsExperience.values
y = df.Salary.values

In [21]:
X.ndim

1

In [25]:
X1 = X.reshape(-1,1)

In [26]:
X1.shape

(30, 1)

In [27]:
X1.shape

(30, 1)

In [28]:
y.shape

(30,)

In [29]:
train_input,test_input,train_output,test_output = train_test_split(X1,y,test_size=.20)

In [30]:
train_input.shape

(24, 1)

In [31]:
test_input.shape

(6, 1)

## Choose ML Algo.

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
lr = LinearRegression()

### train algo. using training data

In [35]:
lr.fit(train_input,train_output)

LinearRegression()

## Evaluate model performance

In [36]:
test = 7.9

In [37]:
t = np.array([[test]])
t.ndim

2

In [39]:
lr.predict(t)

array([100366.3542713])

In [40]:
test_input

array([[4.9],
       [3.7],
       [9.5],
       [5.3],
       [4. ],
       [3. ]])

In [41]:
pred = lr.predict(test_input)

In [42]:
pred

array([ 72156.92345391,  60873.15112696, 115411.38404057,  75918.18089623,
        63694.0942087 ,  54290.95060291])

In [43]:
test_output

array([ 67938.,  57189., 116969.,  83088.,  55794.,  60150.])

In [44]:
from sklearn.metrics import r2_score,mean_squared_error

In [45]:
r2_score(test_output,pred)

0.9343205068178013

In [46]:
mean_squared_error(test_output,pred)

30324117.73967458